Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/Eval:
  Enabled: false

AllCops:
  Exclude:
    - 'data/*'
    - 'lib/sapphire_bot/config.rb'
