Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

AllCops:
  Exclude:
    - 'data/*'
    - 'config.rb'
    - 'example.config.rb'
    - 'sapphire_bot.gemspec'
